### ISSUE TITLE
Map Image not shown on Android

### ISSUE THREAD

**Issue by Monte9** [yelled3/react-native-google-static-map#26]
It's weird, I am seeing the map image on iOS but on Android, I don't see the image.

Looks like it is displaying the component correctly, as when I put a `backgroundColor`, I see it displayed but it just doesn't show the image on Android.

Here is how I am using it: 

```
<TouchableOpacity 
  activeOpacity={0.8}
  onPress={this.openMaps}
>
  <GoogleStaticMap
    style={styles.map}
    latitude={lat}
    longitude={lng}
    zoom={13}
    size={{ width: DEVICE_WIDTH - 60, height: 150 }}
    apiKey={GOOGLE_MAPS_API_KEY}
  />
</TouchableOpacity>
```

Also here are screenshots of what it looks like on iOS vs Android:

<div style="flex: 1; flex-direction: row">
<img width="260" alt="screen shot 2019-02-22 at 6 32 09 pm" src="https://user-images.githubusercontent.com/7840686/53280615-fe5b3b00-36d0-11e9-8f3e-e95292a5b041.png">
<img width="275" alt="screen shot 2019-02-22 at 6 31 31 pm" src="https://user-images.githubusercontent.com/7840686/53280614-fe5b3b00-36d0-11e9-9674-6bc27578c7a0.png">
</div>

My hypothesis is that the Image component is using `source={{ url: .. }}` as opposed to `uri`. I think that when using `url` the image doesn't render on Android. 

Let me know if anyone has any thoughts/suggestions on how to fix this.

**Comment by Monte9** [comment]
@yelled3 any thoughts on this?

**Comment by bvigerzi** [comment]
@Monte9 If you are still stuck on this, the reason we could find was likely because the DEVICE_WIDTH calculated on Android returns a floating point while iOS returns an int. In any case, the width (or height if calculated based on screen size) ends up with a floating point number in Android. This floating point is invalid to send to the static map endpoint, resulting in an error from the Google API. That is why it is unable to display on Android but works on iOS. A simple fix is to just trim the width and height using something like `.toFixed(0)`. I might create a PR for this fix if I get some free time (although development seems silent now on this repo).

**Comment by Monte9** [comment]
That's really useful! I was kinda scratching my head on this as I had no idea why this would be the case only on Android and ended up hiding this feature on Android for launch.

I'll try what you suggested and see if that fixes it for me. Will report back! Thanks for the suggestion. 🙌🏼

**Comment by Monte9** [comment]
Yup, that was exactly right. Here's what I was doing:
`size={{ width: DEVICE_WIDTH - 60, height: 150 }}`
and width returned `351.42857142857144` on Android.

So I update it to `width: Math.floor(DEVICE_WIDTH - 60)` and that fixed it. 

Great find @bvigerzi. Thanks for your help!
